name: expenseTracker

on: [push]

jobs:
  build-node:
    runs-on: windows-latest
    steps:
      - name: Check Node.js and npm versions
        run: |
          node --version
          npm --version
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run script
        run: node index.js