name : expenseTracker

on : [ push ]

jobs:
  job1:
    name: build-node
    runs-on : winodws-latest
    steps:
      - run : node --version
      - run : npm --version
      - uses : actions/cheeckout@v3
      - run : npm install
      - run : node app.js
      
  
