name: Run Node.js script

on:
  schedule:
  # Runs at every minute
    - cron: '*/1 * * * *'

jobs:
  execute-node-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14' # Specify the Node.js version you want to use

    - name: Run script
      run: node ../../index.js # Replace 'your-script.js' with the path to your Node.js file
